#  ┏┓┳┓┏┓┏┓┳┓┏┓┳┳┓┏┓
#  ┃┃┣┫┃┃┃┓┣┫┣┫┃┃┃┗┓
#  ┣┛┛┗┗┛┗┛┛┗┛┗┛ ┗┗┛
#                   

$terminal = ghostty
$fileManager = nautilus
$volumecontrol = pavucontrol
$browser = zen-browser
$music = flatpak run com.spotify.Client

