#  ┏┓┳┓┏┓┏┓┳┓┏┓┳┳┓┏┓
#  ┃┃┣┫┃┃┃┓┣┫┣┫┃┃┃┗┓
#  ┣┛┛┗┗┛┗┛┛┗┛┗┛ ┗┗┛
#                   

$terminal = konsole
$fileManager = nautilus
$volumecontrol = pavucontrol
$browser = zen-browser
$music = $HOME/.spicetify/spicetify watch -q -s &
