#  ┏┓┏┓┏┳┓┏┳┓┳┳┓┏┓┏┓
#  ┗┓┣  ┃  ┃ ┃┃┃┃┓┗┓
#  ┗┛┗┛ ┻  ┻ ┻┛┗┗┛┗┛
#                   

#-----------layout specific settings-------------#
#------------------------------------------------#
dwindle {
    preserve_split = true
    smart_split = false
    smart_resizing = false
    # precise_mouse_move = true
}

master {
  new_status = master
  new_on_top = 1
  mfact = 0.5
}

#---------------gestures----------------------#
#---------------------------------------------#
gestures {
  gesture = 3, horizontal, workspace
  
  workspace_swipe_distance = 500
  workspace_swipe_invert = true
  workspace_swipe_min_speed_to_force = 10
  workspace_swipe_cancel_ratio = 0.5
  workspace_swipe_create_new = true 
  workspace_swipe_forever = true
}

#---------------miscellaneous-----------------#
#---------------------------------------------#
misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  vrr = 2
  mouse_move_enables_dpms = true
  enable_swallow = true
  swallow_regex = ^(com.mitchellh.ghostty)$
  focus_on_activate = false
  initial_workspace_tracking = 0
  background_color = 0x000000
  middle_click_paste = false
}

#----------------others----------------#
#--------------------------------------#
binds {
  workspace_back_and_forth = true
  allow_workspace_cycles = true
  pass_mouse_when_bound = false
}

#Could help when scaling and not pixelating
xwayland {
  enabled = true
  force_zero_scaling = true
}

# render section for Hyprland >= v0.42.0
# render {
#   explicit_sync = 2
#   explicit_sync_kms = 2
#   direct_scanout = false
# }
