#  ┓ ┏┳┳┓┳┓┏┓┓ ┏  ┳┓┳┳┓ ┏┓┏┓
#  ┃┃┃┃┃┃┃┃┃┃┃┃┃  ┣┫┃┃┃ ┣ ┗┓
#  ┗┻┛┻┛┗┻┛┗┛┗┻┛  ┛┗┗┛┗┛┗┛┗┛
#                           

windowrule = match:class .*, suppress_event maximize
windowrule = match:class ^$,match:title ^$,match:xwayland 1,float oning:1,match:fullscreen 0,match:pin 0,no_focus on
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float on, match:class ^(nwg-look)$
windowrule = float on, match:class ^(thunar)$
windowrule = float on, match:class ^(blueman-manager)$

windowrule = opacity 1.0 0.7, match:class ^(blueman-manager)$
windowrule = opacity 1.0 0.7, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = opacity 1.0 0.7, match:class ^(nwg-look)$

windowrule = size 689 400, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = size 826 800, match:class ^(blueman-manager)$

windowrule = float on,match:title ^(Picture-in-Picture)$
windowrule = pin on,match:title ^(Picture-in-Picture)$
windowrule = move 72.5% 70%, match:title ^(Picture-in-Picture)$
windowrule = size 520 320, match:title ^(Picture-in-Picture)$

#---------------kitty network term-------------------------#
#---------------------------------------------------------#
windowrule = float on,match:title ^(TermNmtui)$
windowrule = center on, match:title ^(TermNmtui)$
windowrule = size 800 800, match:title ^(TermNmtui)$


#---------xray--------------#
#---------------------------#
layerrule = xray 1, match:namespace .*

#-----------waybar-------------#
#------------------------------#
layerrule = blur on, match:namespace ^(waybar)$
layerrule = ignore_alpha 0, match:namespace ^(waybar)$
layerrule = ignore_alpha 0.5, match:namespace ^(waybar)$

#-----------swaync-------------#
#------------------------------#
layerrule = blur on, match:namespace ^(swaync-control-center)$
layerrule = blur on, match:namespace ^(swaync-notification-window)$
layerrule = ignore_alpha 0, match:namespace ^(swaync-control-center)$
layerrule = ignore_alpha 0, match:namespace ^(swaync-notification-window)$
layerrule = ignore_alpha 0.5, match:namespace ^(swaync-control-center)$
layerrule = ignore_alpha 0.5, match:namespace ^(swaync-notification-window)$
layerrule = xray 0, match:namespace ^(swaync-control-center)$
layerrule = xray 0, match:namespace ^(swaync-notification-window)$

#----------rofi---------------#
#-----------------------------#
layerrule = blur on, match:namespace ^(rofi)$
layerrule = ignore_alpha 0, match:namespace ^(rofi)$
layerrule = xray 0, match:namespace ^(rofi)$

#---------wlogout------------#
#----------------------------#
layerrule = blur on, match:namespace ^(logout_dialog)$
